### ISSUE TITLE
can't compile using the latest nim version

### ISSUE THREAD

**Issue by dongyu1990** [bluenote10/HiCS#3]
I tried to nimple build the HiCS using nim@1.2.2 or Nim Compiler Version 1.3.5 
and got the following errors:

~/.nimble/pkgs/stringinterpolation-0.1.0/stringinterpolation.nim(69, 24) Error: undeclared identifier: 'expr'

please check, thanks

**Comment by bluenote10** [comment]
That should be easy to solve. Maybe I can push a fix this evening.

**Comment by bluenote10** [comment]
Actually Nim has changed quite a bit since then. I made some minimal adaptions, which makes it compile again for me on Nim devel.
